export const NEW_TESTAMENT_VERSES = [
  { text: "Pero fiel es el Señor, que os afirmará y guardará del mal.", reference: "2 Tesalonicenses 3:3" },
  { text: "Todo lo puedo en Cristo que me fortalece.", reference: "Filipenses 4:13" },
  { text: "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.", reference: "2 Timoteo 1:7" },
  { text: "Y de igual manera el Espíritu nos ayuda en nuestra debilidad.", reference: "Romanos 8:26" },
  { text: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da.", reference: "Juan 14:27" },
  { text: "Estad siempre gozosos. Orad sin cesar. Dad gracias en todo.", reference: "1 Tesalonicenses 5:16-18" },
  { text: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien.", reference: "Romanos 8:28" },
  { text: "Mas buscad primeramente el reino de Dios y su justicia.", reference: "Mateo 6:33" },
  { text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", reference: "Mateo 11:28" },
  { text: "El amor es sufrido, es benigno; el amor no tiene envidia.", reference: "1 Corintios 13:4" },
  { text: "Puestos los ojos en Jesús, el autor y consumador de la fe.", reference: "Hebreos 12:2" },
  { text: "Acerquémonos, pues, confiadamente al trono de la gracia.", reference: "Hebreos 4:16" },
  { text: "En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.", reference: "Juan 16:33" },
  { text: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá.", reference: "Mateo 7:7" },
  { text: "Porque por gracia sois salvos por medio de la fe; es don de Dios.", reference: "Efesios 2:8" },
  { text: "Bienaventurados los de limpio corazón, porque ellos verán a Dios.", reference: "Mateo 5:8" },
  { text: "Si Dios es por nosotros, ¿quién contra nosotros?", reference: "Romanos 8:31" },
  { text: "Y la paz de Dios guardará vuestros corazones y vuestros pensamientos.", reference: "Filipenses 4:7" },
  { text: "Toda la Escritura es inspirada por Dios y útil para enseñar.", reference: "2 Timoteo 3:16" },
  { text: "Justificados, pues, por la fe, tenemos paz para con Dios.", reference: "Romanos 5:1" },
  { text: "No se turbe vuestro corazón; creéis en Dios, creed también en mí.", reference: "Juan 14:1" },
  { text: "Hermanos míos, tened por sumo gozo cuando os halléis en diversas pruebas.", reference: "Santiago 1:2" },
  { text: "Sed, pues, imitadores de Dios como hijos amados.", reference: "Efesios 5:1" },
  { text: "Llevad mi yugo sobre vosotros, y aprended de mí.", reference: "Mateo 11:29" },
  { text: "Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios.", reference: "Mateo 5:9" },
  { text: "Y el Dios de esperanza os llene de todo gozo y paz en el creer.", reference: "Romanos 15:13" },
  { text: "Porque el Hijo del Hombre vino a buscar y a salvar lo que se había perdido.", reference: "Lucas 19:10" },
  { text: "Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.", reference: "Juan 14:6" },
  { text: "Si permanecéis en mí, pedid todo lo que queréis, y os será hecho.", reference: "Juan 15:7" },
  { text: "Y la esperanza no avergüenza; porque el amor de Dios ha sido derramado.", reference: "Romanos 5:5" },
  { text: "No os conforméis a este siglo, sino transformaos por la renovación.", reference: "Romanos 12:2" },
  { text: "Porque donde están dos o tres congregados en mi nombre, allí estoy yo.", reference: "Mateo 18:20" },
  { text: "Mirad cuál amor nos ha dado el Padre.", reference: "1 Juan 3:1" },
  { text: "Cree en el Señor Jesucristo, y serás salvo, tú y tu casa.", reference: "Hechos 16:31" },
  { text: "Si confesamos nuestros pecados, él es fiel y justo para perdonar.", reference: "1 Juan 1:9" },
  { text: "Por nada estéis afanosos, sino sean conocidas vuestras peticiones.", reference: "Filipenses 4:6" },
  { text: "Pero recibiereis poder, cuando haya venido sobre vosotros el Espíritu Santo.", reference: "Hechos 1:8" },
  { text: "Y mi Dios, pues, suplirá todo lo que os falta.", reference: "Filipenses 4:19" },
  { text: "Yo soy la vid, vosotros los pámpanos; el que permanece en mí lleva mucho fruto.", reference: "Juan 15:5" },
  { text: "Porque el fin de la ley es Cristo, para justicia a todo aquel que cree.", reference: "Romanos 10:4" },
  { text: "He peleado la buena batalla, he acabado la carrera, he guardado la fe.", reference: "2 Timoteo 4:7" },
  { text: "La gracia del Señor Jesucristo sea con vuestro espíritu. Amén.", reference: "Filemón 1:25" },
  { text: "Hijitos, guardaos de los ídolos. Amén.", reference: "1 Juan 5:21" },
  { text: "Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros.", reference: "Santiago 4:7" },
  { text: "Sed sobrios, y velad; porque vuestro adversario el diablo anda alrededor.", reference: "1 Pedro 5:8" },
  { text: "He aquí, yo estoy a la puerta y llamo.", reference: "Apocalipsis 3:20" },
  { text: "La gracia de nuestro Señor Jesucristo sea con todos vosotros. Amén.", reference: "Apocalipsis 22:21" },
  { text: "Vuestra gentileza sea conocida de todos los hombres. El Señor está cerca.", reference: "Filipenses 4:5" },
  { text: "Porque la palabra de Dios es viva y eficaz, y más cortante que toda espada.", reference: "Hebreos 4:12" },
  { text: "Y este es el testimonio: que Dios nos ha dado vida eterna.", reference: "1 Juan 5:11" },
  { text: "Ninguno tenga en poco tu juventud, sino sé ejemplo de los creyentes.", reference: "1 Timoteo 4:12" },
  { text: "Y el mundo pasa, y sus deseos; pero el que hace la voluntad de Dios permanece.", reference: "1 Juan 2:17" },
  { text: "Gracia y paz os sean multiplicadas, en el conocimiento de Dios.", reference: "2 Pedro 1:2" },
  { text: "Unánimes entre vosotros; no altivos, sino asociándoos con los humildes.", reference: "Romanos 12:16" },
  { text: "Por lo cual, siendo libre de todos, me he hecho siervo de todos.", reference: "1 Corintios 9:19" },
  { text: "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito.", reference: "Juan 3:16" },
  { text: "En esto conocerán todos que sois mis discípulos, si tuviereis amor.", reference: "Juan 13:35" },
  { text: "Haced todo sin murmuraciones y contiendas.", reference: "Filipenses 2:14" },
  { text: "Permanezca el amor fraternal.", reference: "Hebreos 13:1" },
  { text: "No os olvidéis de la hospitalidad.", reference: "Hebreos 13:2" },
  { text: "Sea vuestro carácter sin avaricia, contentos con lo que tenéis.", reference: "Hebreos 13:5" },
  { text: "Jesucristo es el mismo ayer, y hoy, y por los siglos.", reference: "Hebreos 13:8" },
  { text: "Sed hacedores de la palabra, y no tan solamente oidores.", reference: "Santiago 1:22" },
  { text: "La religión pura y sin mácula delante de Dios el Padre es esta.", reference: "Santiago 1:27" },
  { text: "Así también la fe, si no tiene obras, es muerta en sí misma.", reference: "Santiago 2:17" },
  { text: "Acercaos a Dios, y él se acercará a vosotros.", reference: "Santiago 4:8" },
  { text: "Humillaos delante del Señor, y él os exaltará.", reference: "Santiago 4:10" },
  { text: "Confesaos vuestras ofensas unos a otros, y orad unos por otros.", reference: "Santiago 5:16" },
  { text: "La oración eficaz del justo puede mucho.", reference: "Santiago 5:16" },
  { text: "Bendito el Dios y Padre de nuestro Señor Jesucristo.", reference: "1 Pedro 1:3" },
  { text: "Sed santos, porque yo soy santo.", reference: "1 Pedro 1:16" },
  { text: "Toda carne es como hierba, y toda la gloria del hombre como flor.", reference: "1 Pedro 1:24" },
  { text: "Mas la palabra del Señor permanece para siempre.", reference: "1 Pedro 1:25" },
  { text: "Desead, como niños recién nacidos, la leche espiritual no adulterada.", reference: "1 Pedro 2:2" },
  { text: "Vosotros también, como piedras vivas, sed edificados.", reference: "1 Pedro 2:5" },
  { text: "Honrad a todos. Amad a los hermanos. Temed a Dios. Honrad al rey.", reference: "1 Pedro 2:17" },
  { text: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.", reference: "1 Pedro 5:7" },
  { text: "Y el Dios de toda gracia, os perfeccione, afirme, fortalezca y establezca.", reference: "1 Pedro 5:10" },
  { text: "Y nosotros hemos conocido y creído el amor que Dios tiene para con nosotros.", reference: "1 Juan 4:16" },
  { text: "Dios es amor; y el que permanece en el amor, permanece en Dios.", reference: "1 Juan 4:16" },
  { text: "Nosotros le amamos a él, porque él nos amó primero.", reference: "1 Juan 4:19" },
  { text: "Esta es la victoria que ha vencido al mundo, nuestra fe.", reference: "1 Juan 5:4" },
  { text: "Y esta es la promesa que él nos hizo, la vida eterna.", reference: "1 Juan 2:25" },
  { text: "Amado, yo deseo que tú seas prosperado en todas las cosas.", reference: "3 Juan 1:2" },
  { text: "No tengo yo mayor gozo que este, el oír que mis hijos andan en la verdad.", reference: "3 Juan 1:4" },
  { text: "Conservaos en el amor de Dios.", reference: "Judas 1:21" },
  { text: "Al que es poderoso para guardaros sin caída.", reference: "Judas 1:24" },
  { text: "Yo soy el Alfa y la Omega, principio y fin, dice el Señor.", reference: "Apocalipsis 1:8" },
  { text: "Sé fiel hasta la muerte, y yo te daré la corona de la vida.", reference: "Apocalipsis 2:10" },
  { text: "He aquí, yo vengo pronto; retén lo que tienes.", reference: "Apocalipsis 3:11" },
  { text: "Y el que tiene sed, venga; y el que quiera, tome del agua de la vida.", reference: "Apocalipsis 22:17" },
  { text: "El que da testimonio de estas cosas dice: Ciertamente vengo en breve.", reference: "Apocalipsis 22:20" },
  { text: "Amén; sí, ven, Señor Jesús.", reference: "Apocalipsis 22:20" },
  { text: "Den gracias al Señor, porque él es bueno; su gran amor perdura para siempre.", reference: "Salmos 107:1" },
  { text: "Y todo lo que hagan, de palabra o de obra, háganlo en el nombre del Señor Jesús, dando gracias a Dios el Padre por medio de él.", reference: "Colosenses 3:17" },
  { text: "Canten salmos al Señor, ustedes sus fieles; alaben su santo nombre.", reference: "Salmos 30:4" },
  { text: "Dedíquense a la oración: perseveren en ella con agradecimiento.", reference: "Colosenses 4:2" },
  { text: "Entren por sus puertas con acción de gracias; vengan a sus atrios con himnos de alabanza; denle gracias, bendigan su nombre.", reference: "Salmos 100:4" },
  { text: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe.", reference: "Gálatas 5:22" },
  { text: "El Señor es mi pastor; nada me faltará.", reference: "Salmos 23:1" },
  { text: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino.", reference: "Salmos 119:105" },
  { text: "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal.", reference: "Jeremías 29:11" },
  { text: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá.", reference: "Mateo 7:7" },
  { text: "Mas el que persevere hasta el fin, éste será salvo.", reference: "Mateo 24:13" },
  { text: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios.", reference: "Isaías 41:10" },
  { text: "Todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.", reference: "Colosenses 3:23" },
  { text: "Mas gracias sean dadas a Dios, que nos da la victoria por medio de nuestro Señor Jesucristo.", reference: "1 Corintios 15:57" },
  { text: "Clama a mí, y yo te responderé, y te enseñaré cosas grandes y ocultas que tú no conoces.", reference: "Jeremías 33:3" },
  { text: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", reference: "Salmos 91:1" },
  { text: "Bástate mi gracia; porque mi poder se perfecciona en la debilidad.", reference: "2 Corintios 12:9" },
  { text: "Acerquémonos, pues, confiadamente al trono de la gracia, para alcanzar misericordia.", reference: "Hebreos 4:16" },
  { text: "Porque el amor de Cristo nos constriñe, pensando esto: que si uno murió por todos, luego todos murieron.", reference: "2 Corintios 5:14" },
  { text: "Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones.", reference: "Filipenses 4:7" },
  { text: "Jehová es mi luz y mi salvación; ¿de quién temeré? Jehová es la fortaleza de mi vida.", reference: "Salmos 27:1" },
  { text: "Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas.", reference: "Isaías 40:31" },
  { text: "Encomienda a Jehová tu camino, y confía en él; y él hará.", reference: "Salmos 37:5" },
  { text: "El Señor es bueno, fortaleza en el día de la angustia; y conoce a los que en él confían.", reference: "Nahúm 1:7" },
  { text: "Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estarás conmigo.", reference: "Salmos 23:4" },
  { text: "Bienaventurado el hombre que no anduvo en consejo de malos.", reference: "Salmos 1:1" },
  { text: "Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.", reference: "Salmos 51:10" },
  { text: "Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.", reference: "Mateo 6:33" },
  { text: "Si Dios es por nosotros, ¿quién contra nosotros?", reference: "Romanos 8:31" },
  { text: "Porque la palabra de Dios es viva y eficaz, y más cortante que toda espada de dos filos.", reference: "Hebreos 4:12" },
  { text: "Hermanos, yo mismo no pretendo haberlo ya alcanzado; pero una cosa hago: olvidando lo que queda atrás.", reference: "Filipenses 3:13" },
  { text: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.", reference: "Salmos 46:1" },
  { text: "A Jehová he puesto siempre delante de mí; porque está a mi diestra, no seré conmovido.", reference: "Salmos 16:8" },
  { text: "Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados.", reference: "1 Juan 1:9" },
  { text: "Vuestro corazón no se turbe; creéis en Dios, creed también en mí.", reference: "Juan 14:1" },
  { text: "Puestos los ojos en Jesús, el autor y consumador de la fe.", reference: "Hebreos 12:2" },
  { text: "Si alguno tiene sed, venga a mí y beba.", reference: "Juan 7:37" },
  { text: "El cielo y la tierra pasarán, pero mis palabras no pasarán.", reference: "Mateo 24:35" },
  { text: "Y la esperanza no avergüenza; porque el amor de Dios ha sido derramado en nuestros corazones.", reference: "Romanos 5:5" },
  { text: "Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros.", reference: "Santiago 4:7" },
  { text: "Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón.", reference: "Salmos 37:4" },
  { text: "Bueno es Jehová para con todos, y sus misericordias sobre todas sus obras.", reference: "Salmos 145:9" },
  { text: "Pero recibiereis poder, cuando haya venido sobre vosotros el Espíritu Santo.", reference: "Hechos 1:8" },
  { text: "En esto conocerán todos que sois mis discípulos, si tuviereis amor los unos con los otros.", reference: "Juan 13:35" },
  { text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", reference: "Mateo 11:28" },
  { text: "Mas a todos los que le recibieron, a los que creen en su nombre, les dio potestad de ser hechos hijos de Dios.", reference: "Juan 1:12" },
  { text: "Justificados, pues, por la fe, tenemos paz para con Dios por medio de nuestro Señor Jesucristo.", reference: "Romanos 5:1" },
  { text: "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios.", reference: "Efesios 2:8" },
  { text: "Hagan todo con amor.", reference: "1 Corintios 16:14" },
  { text: "Estén siempre alegres, oren sin cesar, den gracias a Dios en toda situación.", reference: "1 Tesalonicenses 5:16-18" },
  { text: "Ustedes son la luz del mundo. Una ciudad en lo alto de una colina no puede esconderse.", reference: "Mateo 5:14" },
  { text: "Sean amables unos con otros, misericordiosos, perdonándose unos a otros.", reference: "Efesios 4:32" },
  { text: "El amor es paciente, es bondadoso. El amor no es envidioso ni jactancioso ni orgulloso.", reference: "1 Corintios 13:4" },
  { text: "Nadie tiene amor más grande que el dar la vida por sus amigos.", reference: "Juan 15:13" },
  { text: "Por encima de todo, vístanse de amor, que es el vínculo perfecto.", reference: "Colosenses 3:14" }
];
